/* Generated By:JJTree: Do not edit this line. ASTAlterMultilevelFactAddMeasure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTAlterMultilevelFactAddMeasure extends SQLMNode {
  public ASTAlterMultilevelFactAddMeasure(int id) {
    super(id);
  }

  public ASTAlterMultilevelFactAddMeasure(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5d4675d3042d263e3fb0a0995466f05 (do not edit this line) */
