/* Generated By:JJTree: Do not edit this line. ASTAlterMultilevelObjectDropAttribute.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTAlterMultilevelObjectDropAttribute extends SQLMNode {
  public ASTAlterMultilevelObjectDropAttribute(int id) {
    super(id);
  }

  public ASTAlterMultilevelObjectDropAttribute(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=124a01a9cafbf3eb457a3c1fa2e2ce26 (do not edit this line) */
