/* Generated By:JJTree: Do not edit this line. ASTAlterMultilevelFactDropMeasure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTAlterMultilevelFactDropMeasure extends SQLMNode {
  public ASTAlterMultilevelFactDropMeasure(int id) {
    super(id);
  }

  public ASTAlterMultilevelFactDropMeasure(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c6d59a4afca1a3742caf92d5eb93f6d4 (do not edit this line) */
