/* Generated By:JJTree: Do not edit this line. ASTAttributeUnitConversionRule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTAttributeUnitConversionRule extends SQLMNode {
  public ASTAttributeUnitConversionRule(int id) {
    super(id);
  }

  public ASTAttributeUnitConversionRule(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60433e683e535d46d1a6934db11f7744 (do not edit this line) */
