/* Generated By:JJTree: Do not edit this line. ASTAttributeUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTAttributeUnit extends SQLMNode {
  public ASTAttributeUnit(int id) {
    super(id);
  }

  public ASTAttributeUnit(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b9f68537a077262341158a1753b4e9d (do not edit this line) */
