/* Generated By:JJTree: Do not edit this line. ASTAlterMultilevelFact.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTAlterMultilevelFact extends SQLMNode {
  public ASTAlterMultilevelFact(int id) {
    super(id);
  }

  public ASTAlterMultilevelFact(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7fe54d685d45dad022914564a2addb9b (do not edit this line) */
