/* Generated By:JJTree: Do not edit this line. ASTAggregationFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTAggregationFunction extends SQLMNode {
  public ASTAggregationFunction(int id) {
    super(id);
  }

  public ASTAggregationFunction(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fdf4ac4796875a7f7350a6b08dd71e9c (do not edit this line) */
