/* Generated By:JJTree: Do not edit this line. ASTAlterMultilevelObjectAddAttribute.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTAlterMultilevelObjectAddAttribute extends SQLMNode {
  public ASTAlterMultilevelObjectAddAttribute(int id) {
    super(id);
  }

  public ASTAlterMultilevelObjectAddAttribute(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=95cc54e71835515f1ddda82836df0f13 (do not edit this line) */
