/* Generated By:JJTree: Do not edit this line. ASTBulkUpdateMultilevelObjectBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTBulkUpdateMultilevelObjectBlock extends SQLMNode {
  public ASTBulkUpdateMultilevelObjectBlock(int id) {
    super(id);
  }

  public ASTBulkUpdateMultilevelObjectBlock(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb4c8ed595a0604e11b7d794463991ec (do not edit this line) */
