/* Generated By:JJTree: Do not edit this line. ASTBulkCreateMultilevelObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTBulkCreateMultilevelObject extends SQLMNode {
  public ASTBulkCreateMultilevelObject(int id) {
    super(id);
  }

  public ASTBulkCreateMultilevelObject(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f2eda148f73e7e9de5b6e1336426dd7 (do not edit this line) */
