/* Generated By:JJTree: Do not edit this line. ASTBulkUpdateMultilevelObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTBulkUpdateMultilevelObject extends SQLMNode {
  public ASTBulkUpdateMultilevelObject(int id) {
    super(id);
  }

  public ASTBulkUpdateMultilevelObject(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c8f694c07aad769f0b852429d66f703 (do not edit this line) */
