/* Generated By:JJTree: Do not edit this line. ASTBulkUpdateMultilevelFact.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTBulkUpdateMultilevelFact extends SQLMNode {
  public ASTBulkUpdateMultilevelFact(int id) {
    super(id);
  }

  public ASTBulkUpdateMultilevelFact(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7cac730a0ec28e25f85bd2d898acefe (do not edit this line) */
