/* Generated By:JJTree: Do not edit this line. ASTBulkCreateMultilevelFact.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTBulkCreateMultilevelFact extends SQLMNode {
  public ASTBulkCreateMultilevelFact(int id) {
    super(id);
  }

  public ASTBulkCreateMultilevelFact(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27a829128ffc4ef93e72aa8482c6be06 (do not edit this line) */
