/* Generated By:JJTree: Do not edit this line. ASTBulkUpdateMultilevelFactBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTBulkUpdateMultilevelFactBlock extends SQLMNode {
  public ASTBulkUpdateMultilevelFactBlock(int id) {
    super(id);
  }

  public ASTBulkUpdateMultilevelFactBlock(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec39eddd0b20560bc93f7da8d37b5e0e (do not edit this line) */
