/* Generated By:JJTree: Do not edit this line. ASTCubeBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTCubeBlock extends SQLMNode {
  public ASTCubeBlock(int id) {
    super(id);
  }

  public ASTCubeBlock(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=556b2409252076335da5f47ce8374cea (do not edit this line) */
