/* Generated By:JJTree: Do not edit this line. ASTComparisonOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTComparisonOperator extends SQLMNode {
  public ASTComparisonOperator(int id) {
    super(id);
  }

  public ASTComparisonOperator(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9f0eea92c5dad441b2ac59b7b6d2c3fa (do not edit this line) */
