/* Generated By:JJTree: Do not edit this line. ASTClosedMCubeQuery.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTClosedMCubeQuery extends SQLMNode {
  public ASTClosedMCubeQuery(int id) {
    super(id);
  }

  public ASTClosedMCubeQuery(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3beb9384147b8314d8c9423ce6c6ef10 (do not edit this line) */
