/* Generated By:JJTree: Do not edit this line. ASTCubeAlias.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTCubeAlias extends SQLMNode {
  public ASTCubeAlias(int id) {
    super(id);
  }

  public ASTCubeAlias(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff08755ee32abb8143c94f2d8fbb6100 (do not edit this line) */
