/* Generated By:JJTree: Do not edit this line. ASTCreateMultilevelFact.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTCreateMultilevelFact extends SQLMNode {
  public ASTCreateMultilevelFact(int id) {
    super(id);
  }

  public ASTCreateMultilevelFact(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fee55d8aeef6eb902d0eb4a9d06377eb (do not edit this line) */
