/* Generated By:JJTree: Do not edit this line. ASTCreateDimensionHierarchy.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTCreateDimensionHierarchy extends SQLMNode {
  public ASTCreateDimensionHierarchy(int id) {
    super(id);
  }

  public ASTCreateDimensionHierarchy(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51dbed7df0fb72135e3c1dbd0da9d405 (do not edit this line) */
