/* Generated By:JJTree: Do not edit this line. ASTCreateMultilevelObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTCreateMultilevelObject extends SQLMNode {
  public ASTCreateMultilevelObject(int id) {
    super(id);
  }

  public ASTCreateMultilevelObject(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8621c930da14f466e9d92f68363ef480 (do not edit this line) */
