/* Generated By:JJTree: Do not edit this line. ASTDropMultilevelFact.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTDropMultilevelFact extends SQLMNode {
  public ASTDropMultilevelFact(int id) {
    super(id);
  }

  public ASTDropMultilevelFact(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a8297b7b4e110f4d7483578730e0141b (do not edit this line) */
