/* Generated By:JJTree: Do not edit this line. ASTDiceMultilevelObjectIDList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTDiceMultilevelObjectIDList extends SQLMNode {
  public ASTDiceMultilevelObjectIDList(int id) {
    super(id);
  }

  public ASTDiceMultilevelObjectIDList(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30a1195cef49029e58e21fa73d4fe11f (do not edit this line) */
