/* Generated By:JJTree: Do not edit this line. ASTDiceBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTDiceBlock extends SQLMNode {
  public ASTDiceBlock(int id) {
    super(id);
  }

  public ASTDiceBlock(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=096380921ed7d6cf423611fcfc34b96c (do not edit this line) */
