/* Generated By:JJTree: Do not edit this line. ASTDropDimensionHierarchy.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTDropDimensionHierarchy extends SQLMNode {
  public ASTDropDimensionHierarchy(int id) {
    super(id);
  }

  public ASTDropDimensionHierarchy(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb6d60e2174eeef757175ad2e78e9a90 (do not edit this line) */
