/* Generated By:JJTree: Do not edit this line. ASTDefault.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTDefault extends SQLMNode {
  public ASTDefault(int id) {
    super(id);
  }

  public ASTDefault(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e744103c420f212fc9ba06d91de2f79 (do not edit this line) */
