/* Generated By:JJTree: Do not edit this line. ASTDataLength.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTDataLength extends SQLMNode {
  public ASTDataLength(int id) {
    super(id);
  }

  public ASTDataLength(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=61458b26ae35d04de92d820f67c9ad8d (do not edit this line) */
