/* Generated By:JJTree: Do not edit this line. ASTDropMultilevelObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTDropMultilevelObject extends SQLMNode {
  public ASTDropMultilevelObject(int id) {
    super(id);
  }

  public ASTDropMultilevelObject(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b310d6b457421f9ff1bc99068915072f (do not edit this line) */
