/* Generated By:JJTree: Do not edit this line. ASTDropMultilevelCube.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTDropMultilevelCube extends SQLMNode {
  public ASTDropMultilevelCube(int id) {
    super(id);
  }

  public ASTDropMultilevelCube(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06968889ff11adbd649dcf0ee2013808 (do not edit this line) */
