/* Generated By:JJTree: Do not edit this line. ASTInputCubeBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTInputCubeBlock extends SQLMNode {
  public ASTInputCubeBlock(int id) {
    super(id);
  }

  public ASTInputCubeBlock(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dbbb88976c0a871acc67cd12acaaa439 (do not edit this line) */
