/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectLevelParentLevels.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectLevelParentLevels extends SQLMNode {
  public ASTMultilevelObjectLevelParentLevels(int id) {
    super(id);
  }

  public ASTMultilevelObjectLevelParentLevels(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14c02a4e9680a5385dca300a855d44dc (do not edit this line) */
