/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectAttributeValueBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectAttributeValueBlock extends SQLMNode {
  public ASTMultilevelObjectAttributeValueBlock(int id) {
    super(id);
  }

  public ASTMultilevelObjectAttributeValueBlock(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd89100cb69a7fb4dac3af237814eed1 (do not edit this line) */
