/* Generated By:JJTree: Do not edit this line. ASTMultilevelFactConnectionLevelMeasure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelFactConnectionLevelMeasure extends SQLMNode {
  public ASTMultilevelFactConnectionLevelMeasure(int id) {
    super(id);
  }

  public ASTMultilevelFactConnectionLevelMeasure(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c1f193331a138951e970d32b160af1a9 (do not edit this line) */
