/* Generated By:JJTree: Do not edit this line. ASTMultilevelFactConnectionLevelID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelFactConnectionLevelID extends SQLMNode {
  public ASTMultilevelFactConnectionLevelID(int id) {
    super(id);
  }

  public ASTMultilevelFactConnectionLevelID(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99aa8259467db7907316f0bb97c65371 (do not edit this line) */
