/* Generated By:JJTree: Do not edit this line. ASTMetalevelID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMetalevelID extends SQLMNode {
  public ASTMetalevelID(int id) {
    super(id);
  }

  public ASTMetalevelID(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a93edf72516d7560a0af35c3eadb9d45 (do not edit this line) */
