/* Generated By:JJTree: Do not edit this line. ASTMultilevelFactMeasureIdList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelFactMeasureIdList extends SQLMNode {
  public ASTMultilevelFactMeasureIdList(int id) {
    super(id);
  }

  public ASTMultilevelFactMeasureIdList(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c73c292d66924fa8caffd2359d329608 (do not edit this line) */
