/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectLevelHierarchy.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectLevelHierarchy extends SQLMNode {
  public ASTMultilevelObjectLevelHierarchy(int id) {
    super(id);
  }

  public ASTMultilevelObjectLevelHierarchy(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d198f5b059e6b1aa0ba17b6cd4bee5cc (do not edit this line) */
