/* Generated By:JJTree: Do not edit this line. ASTMultilevelCubeID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelCubeID extends SQLMNode {
  public ASTMultilevelCubeID(int id) {
    super(id);
  }

  public ASTMultilevelCubeID(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=063a02119c44090ee02c7c96f0c433f1 (do not edit this line) */
