/* Generated By:JJTree: Do not edit this line. ASTMultilevelCubeCoordinate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelCubeCoordinate extends SQLMNode {
  public ASTMultilevelCubeCoordinate(int id) {
    super(id);
  }

  public ASTMultilevelCubeCoordinate(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4c17c6f3d5604f1d42cb4965fa74f70 (do not edit this line) */
