/* Generated By:JJTree: Do not edit this line. ASTMeasureUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMeasureUnit extends SQLMNode {
  public ASTMeasureUnit(int id) {
    super(id);
  }

  public ASTMeasureUnit(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6bd8913ffa04aa2b7ddf4eb33b66204 (do not edit this line) */
