/* Generated By:JJTree: Do not edit this line. ASTMultilevelFactMeasureID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelFactMeasureID extends SQLMNode {
  public ASTMultilevelFactMeasureID(int id) {
    super(id);
  }

  public ASTMultilevelFactMeasureID(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7201dd65a11fe9b7c0e3ae02d67558f (do not edit this line) */
