/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectLevelAttribute.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectLevelAttribute extends SQLMNode {
  public ASTMultilevelObjectLevelAttribute(int id) {
    super(id);
  }

  public ASTMultilevelObjectLevelAttribute(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb667f5bf84062700e2d51fcf76fb28e (do not edit this line) */
