/* Generated By:JJTree: Do not edit this line. ASTMultilevelFactConnectionLevelHierarchy.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelFactConnectionLevelHierarchy extends SQLMNode {
  public ASTMultilevelFactConnectionLevelHierarchy(int id) {
    super(id);
  }

  public ASTMultilevelFactConnectionLevelHierarchy(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fdf9030ffe7c99ed8e660d10f5450c2d (do not edit this line) */
