/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectAttributeValueAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectAttributeValueAssignment extends SQLMNode {
  public ASTMultilevelObjectAttributeValueAssignment(int id) {
    super(id);
  }

  public ASTMultilevelObjectAttributeValueAssignment(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=211a1e90cc73cd77daa615dfc73ce5c7 (do not edit this line) */
