/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectQualifiedID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectQualifiedID extends SQLMNode {
  public ASTMultilevelObjectQualifiedID(int id) {
    super(id);
  }

  public ASTMultilevelObjectQualifiedID(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e1aac638f3ff67477bd2bbf4f61ee9c1 (do not edit this line) */
