/* Generated By:JJTree: Do not edit this line. ASTMultilevelFactID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelFactID extends SQLMNode {
  public ASTMultilevelFactID(int id) {
    super(id);
  }

  public ASTMultilevelFactID(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4863ab91cafc74d520a6f9a5fd18b22 (do not edit this line) */
