/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectAttributeID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectAttributeID extends SQLMNode {
  public ASTMultilevelObjectAttributeID(int id) {
    super(id);
  }

  public ASTMultilevelObjectAttributeID(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d09a21a5a1f7132625f08c97483b6d7f (do not edit this line) */
