/* Generated By:JJTree: Do not edit this line. ASTMultilevelFactMeasureValueAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelFactMeasureValueAssignment extends SQLMNode {
  public ASTMultilevelFactMeasureValueAssignment(int id) {
    super(id);
  }

  public ASTMultilevelFactMeasureValueAssignment(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fd6a7707910f0a431db786a997025f77 (do not edit this line) */
