/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectLevelID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectLevelID extends SQLMNode {
  public ASTMultilevelObjectLevelID(int id) {
    super(id);
  }

  public ASTMultilevelObjectLevelID(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e85a079edb7869bff5d2977897f035f0 (do not edit this line) */
