/* Generated By:JJTree: Do not edit this line. ASTMultilevelFactConnectionLevelDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelFactConnectionLevelDefinition extends SQLMNode {
  public ASTMultilevelFactConnectionLevelDefinition(int id) {
    super(id);
  }

  public ASTMultilevelFactConnectionLevelDefinition(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb9f918977eec6b858ad9d1b01b2bb63 (do not edit this line) */
