/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectLevelDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectLevelDefinition extends SQLMNode {
  public ASTMultilevelObjectLevelDefinition(int id) {
    super(id);
  }

  public ASTMultilevelObjectLevelDefinition(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e235c291cad3bb4f948c9f2832f94cb0 (do not edit this line) */
