/* Generated By:JJTree: Do not edit this line. ASTMeasureLevelPathList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMeasureLevelPathList extends SQLMNode {
  public ASTMeasureLevelPathList(int id) {
    super(id);
  }

  public ASTMeasureLevelPathList(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dc7a23b8df1cb0192da461ba60c41348 (do not edit this line) */
