/* Generated By:JJTree: Do not edit this line. ASTMeasureLevelPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMeasureLevelPath extends SQLMNode {
  public ASTMeasureLevelPath(int id) {
    super(id);
  }

  public ASTMeasureLevelPath(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f82751a63c41f91fe206a4ec6ad0bba4 (do not edit this line) */
