/* Generated By:JJTree: Do not edit this line. ASTMultilevelObjectParents.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTMultilevelObjectParents extends SQLMNode {
  public ASTMultilevelObjectParents(int id) {
    super(id);
  }

  public ASTMultilevelObjectParents(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f80e15fc220b2e2b56de50c86004dcf6 (do not edit this line) */
