/* Generated By:JJTree: Do not edit this line. ASTNumberValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTNumberValue extends SQLMNode {
  public ASTNumberValue(int id) {
    super(id);
  }

  public ASTNumberValue(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d7169f78a1930d961e330b4885e9133 (do not edit this line) */
