/* Generated By:JJTree: Do not edit this line. ASTNumberType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTNumberType extends SQLMNode {
  public ASTNumberType(int id) {
    super(id);
  }

  public ASTNumberType(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9dbca99490f900e76641de10935aa42 (do not edit this line) */
