/* Generated By:JJTree: Do not edit this line. ASTObjectConstructorList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTObjectConstructorList extends SQLMNode {
  public ASTObjectConstructorList(int id) {
    super(id);
  }

  public ASTObjectConstructorList(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d0803e642d90ac30b9b776bed5d65d70 (do not edit this line) */
