/* Generated By:JJTree: Do not edit this line. ASTObjectConstructor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTObjectConstructor extends SQLMNode {
  public ASTObjectConstructor(int id) {
    super(id);
  }

  public ASTObjectConstructor(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a519fcd0c43b58627e33d8e04e490599 (do not edit this line) */
