/* Generated By:JJTree: Do not edit this line. ASTObjectCollectionConstructor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTObjectCollectionConstructor extends SQLMNode {
  public ASTObjectCollectionConstructor(int id) {
    super(id);
  }

  public ASTObjectCollectionConstructor(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56e9bc73b521521324325bdd1f88e27d (do not edit this line) */
