/* Generated By:JJTree: Do not edit this line. ASTObjectAttributeList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTObjectAttributeList extends SQLMNode {
  public ASTObjectAttributeList(int id) {
    super(id);
  }

  public ASTObjectAttributeList(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6b8c6e015ba767dea2d9d087add17d5 (do not edit this line) */
