/* Generated By:JJTree: Do not edit this line. ASTProjectionBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTProjectionBlock extends SQLMNode {
  public ASTProjectionBlock(int id) {
    super(id);
  }

  public ASTProjectionBlock(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ee9e82f3e35251b50eae05a05a2469dc (do not edit this line) */
