/* Generated By:JJTree: Do not edit this line. ASTRollupUnitConversionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTRollupUnitConversionList extends SQLMNode {
  public ASTRollupUnitConversionList(int id) {
    super(id);
  }

  public ASTRollupUnitConversionList(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=00eb11139a54ab6d44e33ed2012e4eee (do not edit this line) */
