/* Generated By:JJTree: Do not edit this line. ASTRollupExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTRollupExpression extends SQLMNode {
  public ASTRollupExpression(int id) {
    super(id);
  }

  public ASTRollupExpression(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3240bd2ee1f12f3e50ee4fd6aadedc4e (do not edit this line) */
