/* Generated By:JJTree: Do not edit this line. ASTRollupUnitConversion.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTRollupUnitConversion extends SQLMNode {
  public ASTRollupUnitConversion(int id) {
    super(id);
  }

  public ASTRollupUnitConversion(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d7e44f6160fd2dea40388cb8271670f (do not edit this line) */
