/* Generated By:JJTree: Do not edit this line. ASTShared.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTShared extends SQLMNode {
  public ASTShared(int id) {
    super(id);
  }

  public ASTShared(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec72044b38f4f69de5db94fa3786ce86 (do not edit this line) */
