/* Generated By:JJTree: Do not edit this line. ASTSQLSelectStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTSQLSelectStatement extends SQLMNode {
  public ASTSQLSelectStatement(int id) {
    super(id);
  }

  public ASTSQLSelectStatement(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a592d46f4f807d14297aa63a274a8080 (do not edit this line) */
