/* Generated By:JJTree: Do not edit this line. ASTSliceConversionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTSliceConversionExpression extends SQLMNode {
  public ASTSliceConversionExpression(int id) {
    super(id);
  }

  public ASTSliceConversionExpression(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb8717f6e4cd0ac4d5fe09513fe1c286 (do not edit this line) */
