/* Generated By:JJTree: Do not edit this line. ASTSliceExpressionPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTSliceExpressionPath extends SQLMNode {
  public ASTSliceExpressionPath(int id) {
    super(id);
  }

  public ASTSliceExpressionPath(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26aa36baa86114a6ff8c670b79cb1cf2 (do not edit this line) */
