/* Generated By:JJTree: Do not edit this line. ASTSliceExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTSliceExpression extends SQLMNode {
  public ASTSliceExpression(int id) {
    super(id);
  }

  public ASTSliceExpression(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=36d7cc2c8912f323b7e57a741931fef0 (do not edit this line) */
