/* Generated By:JJTree: Do not edit this line. ASTSliceBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTSliceBlock extends SQLMNode {
  public ASTSliceBlock(int id) {
    super(id);
  }

  public ASTSliceBlock(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70ed4fd0abc96ecd155739c60fb5d399 (do not edit this line) */
