/* Generated By:JJTree: Do not edit this line. ASTUpdateMultilevelObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTUpdateMultilevelObject extends SQLMNode {
  public ASTUpdateMultilevelObject(int id) {
    super(id);
  }

  public ASTUpdateMultilevelObject(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5bf494bf1ace9b59a5c832c169cb627d (do not edit this line) */
