/* Generated By:JJTree: Do not edit this line. ASTUserDefinedType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTUserDefinedType extends SQLMNode {
  public ASTUserDefinedType(int id) {
    super(id);
  }

  public ASTUserDefinedType(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=06a537f183b41f3aacfc67cc985516cc (do not edit this line) */
