/* Generated By:JJTree: Do not edit this line. ASTUpdateMultilevelFact.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTUpdateMultilevelFact extends SQLMNode {
  public ASTUpdateMultilevelFact(int id) {
    super(id);
  }

  public ASTUpdateMultilevelFact(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8800894b446f6ed1ab94b67f10c42c24 (do not edit this line) */
