/* Generated By:JJTree: Do not edit this line. ASTVarchar2Type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package at.jku.dke.sqlm.parser;

public
class ASTVarchar2Type extends SQLMNode {
  public ASTVarchar2Type(int id) {
    super(id);
  }

  public ASTVarchar2Type(SQLMParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4788a8427113b67e95176bd6d545d3e (do not edit this line) */
