/* Generated By:JavaCC: Do not edit this line. SQLMParserTreeConstants.java Version 5.0 */
package at.jku.dke.sqlm.parser;

public interface SQLMParserTreeConstants
{
  public int JJTSQLMDOCUMENT = 0;
  public int JJTDATALENGTH = 1;
  public int JJTDATASCALE = 2;
  public int JJTVOID = 3;
  public int JJTUSERDEFINEDTYPE = 4;
  public int JJTVARCHAR2TYPE = 5;
  public int JJTNUMBERTYPE = 6;
  public int JJTOBJECTCOLLECTIONCONSTRUCTOR = 7;
  public int JJTOBJECTCONSTRUCTORLIST = 8;
  public int JJTOBJECTCONSTRUCTOR = 9;
  public int JJTOBJECTATTRIBUTELIST = 10;
  public int JJTSTRINGVALUE = 11;
  public int JJTNUMBERVALUE = 12;
  public int JJTAGGREGATIONFUNCTION = 13;
  public int JJTDEFAULT = 14;
  public int JJTSHARED = 15;
  public int JJTDIMENSIONHIERARCHYID = 16;
  public int JJTMULTILEVELOBJECTID = 17;
  public int JJTMULTILEVELOBJECTQUALIFIEDID = 18;
  public int JJTMULTILEVELOBJECTUNQUALIFIEDID = 19;
  public int JJTMULTILEVELOBJECTLEVELID = 20;
  public int JJTMULTILEVELOBJECTATTRIBUTEID = 21;
  public int JJTMULTILEVELCUBEID = 22;
  public int JJTMULTILEVELFACTID = 23;
  public int JJTMULTILEVELFACTCONNECTIONLEVELID = 24;
  public int JJTMULTILEVELFACTMEASUREID = 25;
  public int JJTMETALEVELID = 26;
  public int JJTBLOCK = 27;
  public int JJTCREATEDIMENSIONHIERARCHY = 28;
  public int JJTCREATEMULTILEVELOBJECT = 29;
  public int JJTMULTILEVELOBJECTPARENTS = 30;
  public int JJTMULTILEVELOBJECTLEVELHIERARCHY = 31;
  public int JJTMULTILEVELOBJECTLEVELDEFINITION = 32;
  public int JJTMULTILEVELOBJECTLEVELPARENTLEVELS = 33;
  public int JJTMULTILEVELOBJECTLEVELATTRIBUTE = 34;
  public int JJTCREATEMULTILEVELCUBE = 35;
  public int JJTMULTILEVELCUBECOORDINATE = 36;
  public int JJTCREATEMULTILEVELFACT = 37;
  public int JJTMULTILEVELFACTCONNECTIONLEVELHIERARCHY = 38;
  public int JJTMULTILEVELFACTCONNECTIONLEVELDEFINITION = 39;
  public int JJTMULTILEVELFACTCONNECTIONLEVELMEASURE = 40;
  public int JJTALTERMULTILEVELOBJECT = 41;
  public int JJTALTERMULTILEVELOBJECTADDATTRIBUTE = 42;
  public int JJTALTERMULTILEVELOBJECTDROPATTRIBUTE = 43;
  public int JJTALTERMULTILEVELFACT = 44;
  public int JJTALTERMULTILEVELFACTADDMEASURE = 45;
  public int JJTALTERMULTILEVELFACTDROPMEASURE = 46;
  public int JJTDROPDIMENSIONHIERARCHY = 47;
  public int JJTDROPMULTILEVELOBJECT = 48;
  public int JJTDROPMULTILEVELCUBE = 49;
  public int JJTDROPMULTILEVELFACT = 50;
  public int JJTUPDATEMULTILEVELOBJECT = 51;
  public int JJTMULTILEVELOBJECTATTRIBUTEVALUEASSIGNMENT = 52;
  public int JJTUPDATEMULTILEVELFACT = 53;
  public int JJTMULTILEVELFACTMEASUREVALUEASSIGNMENT = 54;
  public int JJTBULKCREATEMULTILEVELOBJECT = 55;
  public int JJTBULKUPDATEMULTILEVELOBJECT = 56;
  public int JJTBULKUPDATEMULTILEVELOBJECTBLOCK = 57;
  public int JJTBULKCREATEMULTILEVELFACT = 58;
  public int JJTBULKUPDATEMULTILEVELFACT = 59;
  public int JJTBULKUPDATEMULTILEVELFACTBLOCK = 60;
  public int JJTMULTILEVELOBJECTATTRIBUTEVALUEBLOCK = 61;
  public int JJTMULTILEVELFACTMEASUREVALUEBLOCK = 62;
  public int JJTCLOSEDMCUBEQUERY = 63;
  public int JJTDICEBLOCK = 64;
  public int JJTCUBEBLOCK = 65;
  public int JJTDICEMULTILEVELOBJECTIDLIST = 66;
  public int JJTINPUTCUBEBLOCK = 67;
  public int JJTSLICEBLOCK = 68;
  public int JJTSLICEEXPRESSION = 69;
  public int JJTPROJECTIONBLOCK = 70;
  public int JJTCUBEALIAS = 71;
  public int JJTSLICEEXPRESSIONPATH = 72;
  public int JJTROLLUPEXPRESSION = 73;
  public int JJTMEASURELEVELPATHLIST = 74;
  public int JJTMEASURELEVELPATH = 75;
  public int JJTROLLUPUNITCONVERSIONLIST = 76;
  public int JJTROLLUPUNITCONVERSION = 77;
  public int JJTMULTILEVELFACTMEASUREIDLIST = 78;
  public int JJTMEASUREUNIT = 79;
  public int JJTMEASUREUNITCONVERSIONRULE = 80;
  public int JJTSLICECONVERSIONEXPRESSION = 81;
  public int JJTATTRIBUTEUNIT = 82;
  public int JJTATTRIBUTEUNITCONVERSIONRULE = 83;
  public int JJTCOMPARISONOPERATOR = 84;
  public int JJTSQLSELECTSTATEMENT = 85;


  public String[] jjtNodeName = {
    "SQLMDocument",
    "DataLength",
    "DataScale",
    "void",
    "UserDefinedType",
    "Varchar2Type",
    "NumberType",
    "ObjectCollectionConstructor",
    "ObjectConstructorList",
    "ObjectConstructor",
    "ObjectAttributeList",
    "StringValue",
    "NumberValue",
    "AggregationFunction",
    "Default",
    "Shared",
    "DimensionHierarchyID",
    "MultilevelObjectID",
    "MultilevelObjectQualifiedID",
    "MultilevelObjectUnqualifiedID",
    "MultilevelObjectLevelID",
    "MultilevelObjectAttributeID",
    "MultilevelCubeID",
    "MultilevelFactID",
    "MultilevelFactConnectionLevelID",
    "MultilevelFactMeasureID",
    "MetalevelID",
    "Block",
    "CreateDimensionHierarchy",
    "CreateMultilevelObject",
    "MultilevelObjectParents",
    "MultilevelObjectLevelHierarchy",
    "MultilevelObjectLevelDefinition",
    "MultilevelObjectLevelParentLevels",
    "MultilevelObjectLevelAttribute",
    "CreateMultilevelCube",
    "MultilevelCubeCoordinate",
    "CreateMultilevelFact",
    "MultilevelFactConnectionLevelHierarchy",
    "MultilevelFactConnectionLevelDefinition",
    "MultilevelFactConnectionLevelMeasure",
    "AlterMultilevelObject",
    "AlterMultilevelObjectAddAttribute",
    "AlterMultilevelObjectDropAttribute",
    "AlterMultilevelFact",
    "AlterMultilevelFactAddMeasure",
    "AlterMultilevelFactDropMeasure",
    "DropDimensionHierarchy",
    "DropMultilevelObject",
    "DropMultilevelCube",
    "DropMultilevelFact",
    "UpdateMultilevelObject",
    "MultilevelObjectAttributeValueAssignment",
    "UpdateMultilevelFact",
    "MultilevelFactMeasureValueAssignment",
    "BulkCreateMultilevelObject",
    "BulkUpdateMultilevelObject",
    "BulkUpdateMultilevelObjectBlock",
    "BulkCreateMultilevelFact",
    "BulkUpdateMultilevelFact",
    "BulkUpdateMultilevelFactBlock",
    "MultilevelObjectAttributeValueBlock",
    "MultilevelFactMeasureValueBlock",
    "ClosedMCubeQuery",
    "DiceBlock",
    "CubeBlock",
    "DiceMultilevelObjectIDList",
    "InputCubeBlock",
    "SliceBlock",
    "SliceExpression",
    "ProjectionBlock",
    "CubeAlias",
    "SliceExpressionPath",
    "RollupExpression",
    "MeasureLevelPathList",
    "MeasureLevelPath",
    "RollupUnitConversionList",
    "RollupUnitConversion",
    "MultilevelFactMeasureIdList",
    "MeasureUnit",
    "MeasureUnitConversionRule",
    "SliceConversionExpression",
    "AttributeUnit",
    "AttributeUnitConversionRule",
    "ComparisonOperator",
    "SQLSelectStatement",
  };
}
/* JavaCC - OriginalChecksum=0c1d019a48c17797b54befca54d0902e (do not edit this line) */
